services:
  - type: web
    name: pizzahub-api
    runtime: docker
    dockerfilePath: ./PizzaHubAPI/Dockerfile
    dockerContext: ./PizzaHubAPI
    region: oregon
    plan: free
    branch: back-end-structure
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JwtSettings__SecretKey
        sync: false
      - key: JwtSettings__Issuer
        value: PizzaHub.API
      - key: JwtSettings__Audience
        value: PizzaHub.Clients
      - key: JwtSettings__AccessTokenDurationInMinutes
        value: 15
      - key: JwtSettings__RefreshTokenDurationInDays
        value: 7
      - key: Firebase__ProjectId
        sync: false
      - key: Firebase__PrivateKey
        sync: false
      - key: Firebase__ClientEmail
        sync: false
