// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaHubAPI.Data;

#nullable disable

namespace PizzaHubAPI.Migrations
{
    [DbContext(typeof(PizzaHubContext))]
    [Migration("20251204013200_FixUnidadMedidaType")]
    partial class FixUnidadMedidaType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Este es un snapshot reducido - el modelo completo está en PizzaHubContextModelSnapshot.cs
            modelBuilder.Entity("PizzaHubAPI.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("stock_actual");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("stock_minimo");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.ToTable("insumos");
                });
#pragma warning restore 612, 618
        }
    }
}
